using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagerCheck.Extentions;
using PagerCheck.Models;

namespace PagerCheck.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult LoadTabl(int pIndex, int pSize)
        {

            #region 模拟数据
            PaginationEntity<Title> model = new PaginationEntity<Title>(GetList(), new Pagination { PageSize = pSize, PageIndex = pIndex }) { };
            #endregion
            return PartialView(model);
        }
        public List<Title> GetList()
        {
            #region 模拟数据
            List<Title> list = new List<Title>()
            {
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                 new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="贤心",Mz="汉族",CreateTime="1989-10-14",GY="人生似修行" },
                new Title{ Name="张爱玲",Mz="汉族",CreateTime="1920-09-30",GY="于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…" },
                new Title{ Name="Helen Keller",Mz="拉丁美裔",CreateTime="1880-06-27",GY="Life is either a daring adventure or nothing." },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="岳飞",Mz="汉族",CreateTime="1103-北宋崇宁二年",GY="教科书再滥改，也抹不去“民族英雄”的事实" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
                new Title{ Name="孟子",Mz="华夏族（汉族）",CreateTime="公元前-372年",GY="猿强，则国强。国强，则猿更强！" },
            };
            #endregion
            return list;
        }

    }
}